/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/


package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface HrdbQueryExecutorService {
    Page<Object> executeNoOfDepartments(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeTotalBudget(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeNoOfEmployee(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeEngineeringEmployees(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeMarketingEmployees(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeProfessionalServicesEmployees(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeGeneralAndAdminEmployees(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeSalesEmployees(Pageable pageable) throws QueryParameterMismatchException;
    Page<Object> executeSelectedEmployeeID(Pageable pageable, java.lang.Integer data) throws QueryParameterMismatchException;
    Page<Object> executeNoOfDepartment(Pageable pageable) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

